version: "3"

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:latest
    restart: always
    depends_on:
      - otel-collector
    ports:
      - "9411:9411"

  goserverb:
    build: .
    restart: always
    depends_on:
      - otel-collector
      - zipkin
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=7111479bbb754a45bf014650240204
      - SERVICE_NAME=server-b
      - OTEL_ENDPOINT=otel-collector:4317
    volumes:
      - goapp-modules-cache:/go/pkg/mod

  goservera:
    build:
      context: .
      dockerfile: Dockerfile.servera
    restart: always
    depends_on:
      - goserverb
    ports:
      - "8080:8080"
    environment:
      - SERVERB_HOST=goserverb
      - SERVICE_NAME=server-a
      - OTEL_ENDPOINT=otel-collector:4317
    volumes:
      - goapp-modules-cache:/go/pkg/mod

volumes:
  goapp-modules-cache:
