version: "3"

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  goserverb:
    build: .
    restart: always
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=7111479bbb754a45bf014650240204
    volumes:
      - goapp-modules-cache:/go/pkg/mod

  goservera:
    build:
      context: .
      dockerfile: Dockerfile.servera
    restart: always
    depends_on:
      - goserverb
    ports:
      - "8080:8080"
    environment:
      - SERVERB_HOST=goserverb
    volumes:
      - goapp-modules-cache:/go/pkg/mod

volumes:
  goapp-modules-cache:
