receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlp:
    endpoint: zipkin:9411
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
